### ISSUE TITLE
[TGG Debug] NPE when cheking out Dev-Workspace

### ISSUE THREAD

**Issue by erhanleblebici** [eMoflon/emoflon#574]
When I check out a fresh Dev-Workspace, there is an NPE because of the BreakPointBuilder (cf. stack trace below). Please provide a more robust Debug-Builder:

java.lang.NullPointerException
	at org.moflon.ide.debug.annotation.processor.DebugAnnotation.computeDebugAnnotations(DebugAnnotation.java:134)
	at org.moflon.ide.debug.annotation.processor.builder.BreakpointBuilder.processResource(BreakpointBuilder.java:72)
	at org.moflon.ide.debug.annotation.processor.builder.BreakpointBuilder.visit(BreakpointBuilder.java:89)
	at org.moflon.ide.debug.annotation.processor.builder.BreakpointBuilder.visit(BreakpointBuilder.java:102)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:63)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:47)
	at org.moflon.ide.core.runtime.builders.AbstractBuilder.build(AbstractBuilder.java:67)
	at org.moflon.ide.debug.annotation.processor.builder.BreakpointBuilder.build(BreakpointBuilder.java:54)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by mballhausen** [comment]
Hi,

The corresponding code line is: 
...
134: dependencies.add(root.getProject("TGGLanguage").getLocation().toPortableString() + "/bin");
135: dependencies.add(root.getProject("TGGRuntime").getLocation().toPortableString() + "/bin");
...
I assume that the project "TGGLanguage" and others were renamed to something like "org.moflon...." ? If this is the case, the project name needs to be adapted.

**Comment by anthonyanjorin** [comment]
I think @RolandKluge has established a safer way of accessing the names of our "built-in" projects via their plugin ids or similar.  Not sure if that would help here but this will always be problematic.  One should at least always ask the WorkspaceHelper for such constants so we have them in exactly one place.

**Comment by RolandKluge** [comment]
That's right. I would not use "root.getProject".

The code above the cited lines is almost fine, but (as Tony suggested), I would use the constants in WorkspaceHelper (e.g, PLUGIN_ID_ECORE, PLUGIN_ID_ECORE_XMI).

dependencies.add(FileLocator.getBundleFile(Platform.getBundle("org.apache.log4j")).toString());
         dependencies.add(FileLocator.getBundleFile(Platform.getBundle("org.eclipse.emf.common")).toString());
         dependencies.add(FileLocator.getBundleFile(Platform.getBundle("org.eclipse.emf.ecore")).toString());
         dependencies.add(root.getProject("org.moflon.core.utilities").getLocation().toPortableString() + "/bin");
         dependencies.add(root.getProject("TGGLanguage").getLocation().toPortableString() + "/bin");
         dependencies.add(root.getProject("TGGRuntime").getLocation().toPortableString() + "/bin");

**Comment by RolandKluge** [comment]
Due to the inactivity in this issue, which is **really** annoying and seemingly easy to fix, I decided to fix it. Will be available in eMoflon 2.3.1
