### ISSUE TITLE
Cannot build ClassDiagramToDocumentationIntegration

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#669]
When trying to build ClassDiagramToDocumentationIntegration with the current eMoflon dev. workspace version, the following exception occurs:

    java.lang.RuntimeException: Pattern matching in node [get the reference of lv] failed. Variables: [tgglinkvariable] = org.moflon.tgg.language.impl.TGGLinkVariableImpl@7e106bc8 (name: classes) (bindingOperator: CREATE, bindingSemantics: MANDATORY).
	at org.moflon.tgg.language.compiler.impl.TGGCompilerImpl.createMatchedContextIsAppropriateOperation(TGGCompilerImpl.java:1565)
	at org.moflon.tgg.language.compiler.impl.TGGCompilerImpl.pattern_TGGCompiler_6_7_createisAppropriateactivity_bindingFBBBBB(TGGCompilerImpl.java:7804)
	at org.moflon.tgg.language.compiler.impl.TGGCompilerImpl.pattern_TGGCompiler_6_7_createisAppropriateactivity_bindingAndBlackFBBBBB(TGGCompilerImpl.java:7821)
	at org.moflon.tgg.language.compiler.impl.TGGCompilerImpl.createMatchedContextOperationalRules(TGGCompilerImpl.java:1883)
	at org.moflon.tgg.language.compiler.impl.TGGCompilerImpl.pattern_TGGCompiler_12_6_createforwardmatchedcontextoperationalrules_expressionBBB(TGGCompilerImpl.java:9927)
	at org.moflon.tgg.language.compiler.impl.TGGCompilerImpl.deriveOperationalRules(TGGCompilerImpl.java:2661)
	at org.moflon.ide.core.runtime.codegeneration.IntegrationCodeGenerator.processTGG(IntegrationCodeGenerator.java:224)
	at org.moflon.ide.core.runtime.codegeneration.IntegrationCodeGenerator.generateCode(IntegrationCodeGenerator.java:85)
	at org.moflon.ide.core.util.BuilderHelper.generateCodeInOrder(BuilderHelper.java:96)
	at org.moflon.ide.ui.admin.handlers.EMoflonBuildJob.runInWorkspace(EMoflonBuildJob.java:61)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

URL to MM project: https://dev.kom.e-technik.tu-darmstadt.de/svn/es_emoflon-tests/trunk/language_suite/Amalgamation/CDtoDocumentation
(Repo project is not versioned, currently.)

FYI: @anthonyanjorin

**Comment by erhanleblebici** [comment]
I can't reproduce the error but it happened to me once, too. A new build helped. I don't close the issue and hope everything is alright when we generate Democles patterns directly.

**Comment by RolandKluge** [comment]
I close this issue - in case it happens again, we just re-open it.
