### ISSUE TITLE
ecore importer: DummyTest ecore-file can't be exported after succesful import.

### ISSUE THREAD

**Issue by LarsK01** [eMoflon/emoflon#675]
When I imported the DummyTest ecore-file and want to export it afterwards, the export fails. The DummyTest ecore-file was not modified (as attachment the ecore-file: [DummyTest.zip](https://github.com/eMoflon/emoflon/files/168773/DummyTest.zip)).

Following exceptions has been thrown:

"org.eclipse.core.runtime.CoreException: Exception during export.
	at org.moflon.ide.core.runtime.builders.MetamodelBuilder.processResource(MetamodelBuilder.java:93)
	at org.moflon.ide.core.runtime.builders.AbstractBuilder.build(AbstractBuilder.java:56)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:262)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:402)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:556)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:534)
	at org.eclipse.core.internal.resources.Project.build(Project.java:111)
	at org.moflon.ide.ui.admin.handlers.EMoflonBuildJob.cleanAndBuild(EMoflonBuildJob.java:87)
	at org.moflon.ide.ui.admin.handlers.EMoflonBuildJob.runInWorkspace(EMoflonBuildJob.java:53)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.moflon.core.utilities.UncheckedCoreException: org.eclipse.core.runtime.CoreException: Project org.emoflon.importedecore.org.moflon.test.dummytest is missing
	at org.moflon.ide.core.runtime.ResourceFillingMocaToMoflonTransformation.reportError(ResourceFillingMocaToMoflonTransformation.java:264)
	at org.moflon.ide.core.runtime.ResourceFillingMocaToMoflonTransformation.handleOrReportMissingProject(ResourceFillingMocaToMoflonTransformation.java:249)
	at org.moflon.ide.core.runtime.ResourceFillingMocaToMoflonTransformation.handleOutermostPackage(ResourceFillingMocaToMoflonTransformation.java:104)
	at org.moflon.core.mocatomoflon.impl.ExporterImpl.pattern_Exporter_22_7_PostprocessOutermostPackage_expressionBBB(ExporterImpl.java:5419)
	at org.moflon.core.mocatomoflon.impl.ExporterImpl.mocaToEcore(ExporterImpl.java:1935)
	at org.moflon.ide.core.runtime.builders.MetamodelBuilder.processResource(MetamodelBuilder.java:84)
	... 18 more
Caused by: org.eclipse.core.runtime.CoreException: Project org.emoflon.importedecore.org.moflon.test.dummytest is missing
	at org.moflon.core.utilities.UncheckedCoreException.<init>(UncheckedCoreException.java:24)
	... 24 more"

**Comment by SchroedingersCatIsUndead** [comment]
fixed
