### ISSUE TITLE
Problem while visualizing demo example

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#699]
While going through the handbook, Part III, SDMs, the following exception occurred while trying to visualize an SDM:

java.lang.NullPointerException

            at net.sourceforge.plantuml.eclipse.utils.WorkbenchUtil.getShell(WorkbenchUtil.java:46)

            at net.sourceforge.plantuml.eclipse.utils.WorkbenchUtil.errorBox(WorkbenchUtil.java:128)

            at net.sourceforge.plantuml.eclipse.model.Diagram.getImage(Diagram.java:119)

            at net.sourceforge.plantuml.eclipse.actions.GenerateAction$4.run(GenerateAction.java:225)

            at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Ecore file:     
[LearningBoxLanguage.zip](https://github.com/eMoflon/emoflon/files/234132/LearningBoxLanguage.zip)

@anthonyanjorin FYI

**Comment by anthonyanjorin** [comment]
Couldn't reproduce this.  Let's hope the bug is simply gone :)
