### ISSUE TITLE
NPE during checking out of Handbook Final

### ISSUE THREAD

**Issue by RolandKluge** [eMoflon/emoflon#765]
Using the new build process in an Eclipse runtime instance and downloading 'Handbook Final', I get the following NPE - just for documentation:
```
java.lang.NullPointerException
	at org.moflon.ide.core.runtime.ProjectDependencyAnalyzer.analyzeDependencies(ProjectDependencyAnalyzer.java:50)
	at org.moflon.ide.core.runtime.ProjectDependencyAnalyzer.run(ProjectDependencyAnalyzer.java:87)
	at org.gervarro.eclipse.task.ProgressMonitoringJob.executeSyncSubTasks(ProgressMonitoringJob.java:88)
	at org.moflon.tgg.mosl.builder.MoslTGGBuilder.processResource(MoslTGGBuilder.java:62)
	at org.gervarro.eclipse.workspace.util.RelevantElementCollectingBuilder.postprocess(RelevantElementCollectingBuilder.java:54)
	at org.moflon.ide.core.runtime.builders.AbstractVisitorBuilder.postprocess(AbstractVisitorBuilder.java:41)
	at org.gervarro.eclipse.workspace.util.RelevantElementCollectingBuilder.postprocess(RelevantElementCollectingBuilder.java:1)
	at org.gervarro.eclipse.workspace.util.VisitorDrivenProjectBuilder.build(VisitorDrivenProjectBuilder.java:51)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by RolandKluge** [comment]
It turned out that the EResource metamodelResource in ProjectDependencyAnalyzer is null.

**Comment by RolandKluge** [comment]
The underlying problem is that the created *outermostPackage* has not been added to an *EResource* yet, when the analyzer is created in org.moflon.ide.core.runtime.BasicResourceFillingMocaToMoflonTransformation.handleOutermostPackage(Node, EPackage)

I currently do not know how to solve this issue. @gervarro Can you check this?

**Comment by RolandKluge** [comment]
I have now committet a hack. The problem was twofold: the Resource of the MOCA tree was null and even if we identify the resource correctly, its resource set is removed during the 'unloading' of the MOCA tree. I have added a field that caches the Moca2Moflon resource set.

Probably, this is not the best solution (I have added a @gervarro TODO).

**Comment by gervarro** [comment]
I am going to revert to the old implementation of ProjectDependencyAnalyzer.

**Comment by gervarro** [comment]
After reverting ProjectDependencyAnalyzer to the old implementation, this exception is not thrown.
